name: PublishDockerImage

# Run whenever the publish job runs
on:
  push:
    tags:
      - "v*_*"

jobs:
  push_to_registry:
    name: Build and push image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Parse tag
        run: |
          TAG=${{ github.ref_name }}
          SPLIT=(${TAG//_/ })
          echo "TF_VER=${SPLIT[1]}" >> $GITHUB_ENV
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/cptkirk/rover:${{ github.ref_name }}
          build-args: 
            TF_VERSION=${{ env.TF_VER }}
