name: PublishDockerImage

# Run whenever the publish job runs
on:
  push:
    tags:
      - "v*"

jobs:
  push_to_registry:
    name: Build and push image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Parse tag
        run: |
          IN=${{ github.ref_name }}
          SPLIT=(${IN//_/ })
          TF_VER=${arrIN[1]}
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: cptkirk/rover:${{ github.ref_name }}
          build-args: 
            TF_VERSION=$TF_VER
